name: openapi_code_builder
description: Generate Dtos, client and server scaffolds for openapi specs.
version: 1.3.0+1
homepage: https://github.com/hpoul/openapi_dart/tree/master/packages/openapi_code_builder

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  logging: ">=1.0.1 <2.0.0"
  logging_appenders: ^1.1.0
  meta: ">=1.5.0 <2.0.0"
  openapi_base: ">=1.1.0 <2.0.0"
  path: ">=1.8.0 <2.0.0"
  dart_style: ">=2.0.1 <3.0.0"
  code_builder: ">=4.0.0 <5.0.0"
  build: ">=2.0.2 <3.0.0"
  source_gen: ">=1.0.2 <2.0.0"
  open_api_forked: ^3.0.0+6
  yaml: ">=3.1.0 <4.0.0"
  json_annotation: ">=4.0.1 <6.0.0"
  recase: ^4.1.0
  quiver: ">=3.0.1 <4.0.0"
  built_collection: ">=5.1.0 <6.0.0"
  collection: ">=1.15.0 <2.0.0"
  test:

dev_dependencies:
  lints: ^3.0.0

dependency_overrides:
  analyzer: ^6.4.1
