name: openapi_code_builder_example
description: Example use of openapi code builder.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logging: ^1.0.0
  logging_appenders: ^1.0.0
  openapi_base:
    path: ../../openapi_base

dev_dependencies:
  openapi_code_builder:
    path: ../
  json_serializable: ^6.9.0
  freezed: ^2.4.6
  build_runner: ^2.4.8
  lints: ^5.0.0

dependency_overrides:
  openapi_base:
    path: ../../openapi_base
  open_api_forked:
    path: ../../../deps/open-api-dart
